INSERT INTO TB_VEHICLE(LICENSE_PLATE, MODEL) VALUES( 'ABD9H37','Gol');
INSERT INTO TB_VEHICLE(LICENSE_PLATE, MODEL) VALUES( 'FFE1G88','Uno');
INSERT INTO TB_VEHICLE(LICENSE_PLATE, MODEL) VALUES( 'DDD9H99','HB20');
INSERT INTO TB_VEHICLE(LICENSE_PLATE, MODEL) VALUES( 'BDG4X00','Hilux');

INSERT INTO TB_PARKING_SPACE(NUMBER, VEHICLE_TYPE, IS_PCD) VALUES('1-A','CAR',0);
INSERT INTO TB_PARKING_SPACE(NUMBER, VEHICLE_TYPE, IS_PCD) VALUES('2-A','CAR',0);
INSERT INTO TB_PARKING_SPACE(NUMBER, VEHICLE_TYPE, IS_PCD) VALUES('3-A','CAR',0);
INSERT INTO TB_PARKING_SPACE(NUMBER, VEHICLE_TYPE, IS_PCD) VALUES('4-C','CAR',0);
INSERT INTO TB_PARKING_SPACE(NUMBER, VEHICLE_TYPE, IS_PCD) VALUES('5-C','PICKUP',0);
INSERT INTO TB_PARKING_SPACE(NUMBER, VEHICLE_TYPE, IS_PCD) VALUES('6-C','PICKUP',0);
INSERT INTO TB_PARKING_SPACE(NUMBER, VEHICLE_TYPE, IS_PCD) VALUES('1-B','CAR',1);
INSERT INTO TB_PARKING_SPACE(NUMBER, VEHICLE_TYPE, IS_PCD) VALUES('2-B','CAR',1);
INSERT INTO TB_PARKING_SPACE(NUMBER, VEHICLE_TYPE, IS_PCD) VALUES('3-B','CAR',0);
INSERT INTO TB_PARKING_SPACE(NUMBER, VEHICLE_TYPE, IS_PCD) VALUES('1-M','MOTORCICLE',0);
INSERT INTO TB_PARKING_SPACE(NUMBER, VEHICLE_TYPE, IS_PCD) VALUES('2-M','MOTORCICLE',0);
INSERT INTO TB_PARKING_SPACE(NUMBER, VEHICLE_TYPE, IS_PCD) VALUES('3-M','MOTORCICLE',0);
INSERT INTO TB_PARKING(name)values('Carlos-Car Estacionamento');
INSERT INTO TB_PARKING_ITEM(ID_PARKING, ID_PARKING_SPACE, STATUS) SELECT 1, T.ID_PARKING_SPACE, 'FREE' FROM TB_PARKING_SPACE T
INSERT INTO TB_PARKING_VALUES(VALUE_MINUTE, VEHICLE_TYPE, IS_ACTIVE) VALUES(0.2, 'CAR',1);
INSERT INTO TB_PARKING_VALUES(VALUE_MINUTE, VEHICLE_TYPE, IS_ACTIVE) VALUES(0.1, 'MOTORCICLE',1);
INSERT INTO TB_PARKING_VALUES(VALUE_MINUTE, VEHICLE_TYPE, IS_ACTIVE) VALUES(0.4, 'PICKUP',1);